/* Smart PDF Studio - isolated additional tools */
(function(){
const T=[["word2pdf","Word to PDF"],["excel2pdf","Excel to PDF"],["ppt2pdf","PowerPoint to PDF"],["pdf2ppt","PDF to PowerPoint"],["pdf2jpg","PDF to JPG"],["pdf2png","PDF to PNG"],["jpg2pdf","JPG/PNG to PDF"],["pdfCrop","PDF Cropper"],["pdfResize","PDF Resize"],["qrGenerator","QR Code Generator"],["qrScanner","QR Code Scanner"],["pdfText","PDF Text Extractor"],["pdfImages","PDF Image Extractor"],["pdfGrayscale","PDF Grayscale"],["pdfCompare","PDF Compare"],["pdfMeta","PDF Metadata Viewer"],["blankRemove","Blank Page Remover"],["pdfHeaderFooter","PDF Header & Footer"],["batesNumber","Bates Numbering"],["pdfMarkdown","PDF to Markdown"]];
const $=id=>document.getElementById(id),load=(u,c)=>c()?Promise.resolve():new Promise((ok,no)=>{let s=document.createElement("script");s.src=u;s.onload=()=>c()?ok():no(Error("Library could not be loaded"));s.onerror=()=>no(Error("Library could not be loaded"));document.head.appendChild(s)}),bytes=f=>f.arrayBuffer(),dl=(b,n,t)=>{let x=b instanceof Blob?b:new Blob([b],{type:t||"application/octet-stream"}),a=document.createElement("a");a.href=URL.createObjectURL(x);a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
const O=document.createElement("div");O.style.cssText="display:none;position:fixed;inset:0;z-index:99999;background:rgba(15,23,42,.65);padding:18px;overflow:auto";document.body.appendChild(O);
function show(id,name){O.innerHTML='<div style="max-width:680px;margin:4vh auto;background:white;border-radius:20px;padding:22px;font-family:system-ui"><div style="display:flex;justify-content:space-between"><h2>'+name+'</h2><button id="nxClose">✕</button></div><div id="nxForm"></div><button id="nxRun" style="margin-top:16px;width:100%;padding:12px;background:#0284c7;color:white;border:0;border-radius:10px;font-weight:700">Process & Download</button><pre id="nxStatus" style="white-space:pre-wrap;color:#475569"></pre></div>';O.style.display="block";$("nxClose").onclick=()=>O.style.display="none";let f=$("nxForm"),F=(id,a,m)=>'<input id="'+id+'" type="file" accept="'+a+'" '+(m?"multiple":"")+' style="width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:9px">';if(/2pdf$/.test(id)&&id!=="pdf2ppt"&&id!=="jpg2pdf")f.innerHTML=F(id+"File",id==="word2pdf"?".docx":id==="excel2pdf"?".xlsx,.xls,.csv":".pptx");else if(["pdf2ppt","pdf2jpg","pdf2png","pdfText","pdfImages","pdfGrayscale","pdfMeta","blankRemove","pdfMarkdown"].includes(id))f.innerHTML=F(id+"File",".pdf");else if(id==="jpg2pdf")f.innerHTML=F("jpg2pdfFiles","image/jpeg,image/png",1);else if(id==="pdfCrop")f.innerHTML=F("pdfCropFile",".pdf")+'<input id="crop" type="number" value="10" placeholder="Crop margin" style="margin-top:10px;width:100%;padding:10px">';else if(id==="pdfResize")f.innerHTML=F("pdfResizeFile",".pdf")+'<select id="size" style="margin-top:10px;width:100%;padding:10px"><option value="a4">A4</option><option value="letter">Letter</option><option value="a5">A5</option></select>';else if(id==="qrGenerator")f.innerHTML='<textarea id="qrText" rows="4" placeholder="URL or text" style="width:100%;padding:10px"></textarea><input id="qrSize" value="512" type="number" style="margin-top:10px;width:100%;padding:10px">';else if(id==="qrScanner")f.innerHTML=F("qrScanFile","image/*");else if(id==="pdfCompare")f.innerHTML=F("pdfCompareA",".pdf")+F("pdfCompareB",".pdf");else if(id==="pdfHeaderFooter")f.innerHTML=F("pdfHeaderFooterFile",".pdf")+'<input id="head" placeholder="Header" style="margin-top:10px;width:100%;padding:10px"><input id="foot" placeholder="Footer" style="margin-top:10px;width:100%;padding:10px">';else if(id==="batesNumber")f.innerHTML=F("batesFile",".pdf")+'<input id="pre" value="CASE-" style="margin-top:10px;width:100%;padding:10px"><input id="start" type="number" value="1" style="margin-top:10px;width:100%;padding:10px">';$("nxRun").onclick=()=>run(id)}
async function PDF(f){await load("https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js",()=>!!window.pdfjsLib);return pdfjsLib.getDocument({data:await bytes(f)}).promise}
async function text(f){let E=await PDF(f),a=[];for(let i=1;i<=E.numPages;i++){let c=await(await E.getPage(i)).getTextContent();a.push(c.items.map(x=>x.str).join(" "))}return a}
async function pages(f,fn){let E=await PDF(f);for(let i=1;i<=E.numPages;i++){let g=await E.getPage(i),v=g.getViewport({scale:2}),c=document.createElement("canvas");c.width=v.width;c.height=v.height;await g.render({canvasContext:c.getContext("2d"),viewport:v}).promise;await fn(c,i)}}
async function run(id){let s=document.getElementById("toolStatus")||document.getElementById("nxStatus");if(!s){s=document.createElement("div");s.id="toolStatus";s.className="mt-4 text-sm text-slate-600";let host=document.querySelector("[data-new-tool-status]")||document.querySelector("#toolPanel")||document.querySelector("main");if(host)host.appendChild(s)}const setStatus=(v)=>{if(s)setStatus(v};try{setStatus("Processing...");if(id==="word2pdf"){await load("https://cdn.jsdelivr.net/npm/mammoth@1.8.0/mammoth.browser.min.js",()=>!!window.mammoth);let f=$("word2pdfFile").files[0],r=await mammoth.convertToHtml({arrayBuffer:await bytes(f)}),d=document.createElement("div");d.innerHTML=r.value;d.style.cssText="position:fixed;left:-10000px;width:794px;background:white;padding:40px";document.body.appendChild(d);let c=await html2canvas(d,{scale:2}),p=new jspdf.jsPDF({unit:"mm",format:"a4"});document.body.removeChild(d);p.addImage(c.toDataURL("image/jpeg"),"JPEG",10,10,190,277);p.save("word-to-pdf.pdf")}
else if(id==="excel2pdf"){await load("https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js",()=>!!window.XLSX);let f=$("excel2pdfFile").files[0],w=XLSX.read(await bytes(f),{type:"array"}),p=new jspdf.jsPDF({unit:"mm",format:"a4",orientation:"landscape"});w.SheetNames.forEach((n,k)=>{if(k)p.addPage();let y=12;p.setFontSize(9);XLSX.utils.sheet_to_json(w.Sheets[n],{header:1,defval:""}).slice(0,70).forEach(r=>{p.text(r.map(x=>String(x)).join(" | ").slice(0,170),8,y);y+=5;if(y>195){p.addPage();y=10}})});p.save("excel-to-pdf.pdf")}
else if(id==="ppt2pdf"){await load("https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js",()=>!!window.JSZip);let z=await JSZip.loadAsync(await bytes($("ppt2pdfFile").files[0])),p=new jspdf.jsPDF({unit:"mm",format:"a4"}),ss=Object.keys(z.files).filter(x=>/^ppt\/slides\/slide\d+\.xml$/.test(x)).sort();ss.forEach(async()=>{});for(let i=0;i<ss.length;i++){if(i)p.addPage();let d=new DOMParser().parseFromString(await z.files[ss[i]].async("text"),"application/xml"),y=20;p.setFontSize(14);p.text("Slide "+(i+1),10,y);y+=10;for(let n of d.getElementsByTagNameNS("*","t")){let q=n.textContent.trim();if(q){p.text(p.splitTextToSize(q,180),10,y);y+=8}}}p.save("powerpoint-to-pdf.pdf")}
else if(id==="pdf2ppt"){await load("https://cdn.jsdelivr.net/npm/pptxgenjs@3.12.0/dist/pptxgen.min.js",()=>!!window.PptxGenJS);let p=new PptxGenJS;p.layout="LAYOUT_WIDE";await pages($("pdf2pptFile").files[0],async(c)=>p.addSlide().addImage({data:c.toDataURL("image/png"),x:0,y:0,w:13.333,h:7.5}));await p.writeFile({fileName:"pdf-to-powerpoint.pptx"})}
else if(id==="pdf2jpg"||id==="pdf2png"){let jpg=id==="pdf2jpg";await pages($(id+"File").files[0],async(c,i)=>dl(await new Promise(r=>c.toBlob(r,jpg?"image/jpeg":"image/png",.92)),"page-"+i+(jpg?".jpg":".png")))}
else if(id==="jpg2pdf"){let p=await PDFLib.PDFDocument.create();for(let f of $("jpg2pdfFiles").files){let im=f.type==="image/jpeg"?await p.embedJpg(await bytes(f)):await p.embedPng(await bytes(f)),q=Math.min(595/im.width,842/im.height),g=p.addPage([595,842]);g.drawImage(im,{x:(595-im.width*q)/2,y:(842-im.height*q)/2,width:im.width*q,height:im.height*q})}dl(await p.save(),"images-to-pdf.pdf")}
else if(id==="pdfCrop"){let p=await PDFLib.PDFDocument.load(await bytes($("pdfCropFile").files[0])),m=+$("crop").value||0;p.getPages().forEach(g=>g.setCropBox(m,m,g.getWidth()-2*m,g.getHeight()-2*m));dl(await p.save(),"cropped.pdf")}
else if(id==="pdfResize"){let p=await PDFLib.PDFDocument.load(await bytes($("pdfResizeFile").files[0])),q=$("size").value,d=q==="letter"?[612,792]:q==="a5"?[420,595]:[595,842];p.getPages().forEach(g=>g.setSize(...d));dl(await p.save(),"resized.pdf")}
else if(id==="qrGenerator"){let t=$("qrText").value.trim(),z=$("qrSize").value||512;if(!t)throw Error("Enter text");dl(await(await fetch("https://api.qrserver.com/v1/create-qr-code/?size="+z+"x"+z+"&data="+encodeURIComponent(t))).blob(),"qr-code.png")}
else if(id==="qrScanner"){await load("https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.js",()=>!!window.jsQR);let f=$("qrScanFile").files[0],im=await new Promise((r,e)=>{let x=new Image;x.onload=()=>r(x);x.onerror=e;x.src=URL.createObjectURL(f)}),c=document.createElement("canvas");c.width=im.naturalWidth;c.height=im.naturalHeight;c.getContext("2d").drawImage(im,0,0);let q=jsQR(c.getContext("2d").getImageData(0,0,c.width,c.height).data,c.width,c.height);if(!q)throw Error("No QR code detected");setStatus(q.data;return}
else if(id==="pdfText"||id==="pdfMarkdown"){let a=await text($(id+"File").files[0]),o=id==="pdfMarkdown"?a.map((x,i)=>"## Page "+(i+1)+"\n\n"+x).join("\n\n"):a.join("\n\n");dl(o+"\n",id==="pdfMarkdown"?"document.md":"extracted.txt","text/plain");setStatus(o;return}
else if(id==="pdfImages"){await pages($("pdfImagesFile").files[0],async(c,i)=>dl(await new Promise(r=>c.toBlob(r,"image/png")),"page-"+i+".png"))}
else if(id==="pdfGrayscale"){let E=await PDF($("pdfGrayscaleFile").files[0]),p=await PDFLib.PDFDocument.create();for(let i=1;i<=E.numPages;i++){let g=await E.getPage(i),v=g.getViewport({scale:1.4}),c=document.createElement("canvas");c.width=v.width;c.height=v.height;let x=c.getContext("2d");await g.render({canvasContext:x,viewport:v}).promise;let d=x.getImageData(0,0,c.width,c.height);for(let j=0;j<d.data.length;j+=4){let q=.299*d.data[j]+.587*d.data[j+1]+.114*d.data[j+2];d.data[j]=d.data[j+1]=d.data[j+2]=q}x.putImageData(d,0,0);let im=await p.embedPng(await new Promise(r=>c.toBlob(r,"image/png"))),pg=p.addPage([v.width*.75,v.height*.75]);pg.drawImage(im,{x:0,y:0,width:pg.getWidth(),height:pg.getHeight()})}dl(await p.save(),"grayscale.pdf")}
else if(id==="pdfCompare"){let a=await text($("pdfCompareA").files[0]),b=await text($("pdfCompareB").files[0]),d=[];for(let i=0;i<Math.max(a.length,b.length);i++)if(a[i]!==b[i])d.push("Page "+(i+1)+"\nA: "+(a[i]||"")+"\nB: "+(b[i]||""));let o=d.join("\n\n")||"No text differences found";dl(o,"pdf-comparison.txt","text/plain");setStatus(o;return}
else if(id==="pdfMeta"){let p=await PDFLib.PDFDocument.load(await bytes($("pdfMetaFile").files[0])),o=["Title: "+(p.getTitle?.()||""),"Author: "+(p.getAuthor?.()||""),"Subject: "+(p.getSubject?.()||""),"Keywords: "+(p.getKeywords?.()||"")].join("\n");dl(o,"pdf-metadata.txt","text/plain");setStatus(o;return}
else if(id==="blankRemove"){let f=$("blankRemoveFile").files[0],E=await PDF(f),p=await PDFLib.PDFDocument.load(await bytes(f)),keep=[];for(let i=1;i<=E.numPages;i++){let g=await E.getPage(i),v=g.getViewport({scale:.4}),c=document.createElement("canvas");c.width=v.width;c.height=v.height;await g.render({canvasContext:c.getContext("2d"),viewport:v}).promise;let d=c.getContext("2d").getImageData(0,0,c.width,c.height).data,ink=0;for(let j=0;j<d.length;j+=16)if(d[j]<245)ink++;if(ink>d.length/2000)keep.push(i-1)}let q=await PDFLib.PDFDocument.create();(await q.copyPages(p,keep)).forEach(x=>q.addPage(x));dl(await q.save(),"without-blank-pages.pdf")}
else if(id==="pdfHeaderFooter"){let p=await PDFLib.PDFDocument.load(await bytes($("pdfHeaderFooterFile").files[0]));p.getPages().forEach(g=>{if($("head").value)g.drawText($("head").value,{x:24,y:g.getHeight()-24,size:9});if($("foot").value)g.drawText($("foot").value,{x:24,y:14,size:9})});dl(await p.save(),"header-footer.pdf")}
else if(id==="batesNumber"){let p=await PDFLib.PDFDocument.load(await bytes($("batesFile").files[0])),n=+$("start").value||1;p.getPages().forEach((g,i)=>g.drawText(($("pre").value||"CASE-")+String(n+i).padStart(6,"0"),{x:g.getWidth()-110,y:18,size:9}));dl(await p.save(),"bates-numbered.pdf")}
setStatus("Completed successfully."
}catch(e){setStatus("Error: "+(e.message||e)}}
const NT_NAMES={en:{word2pdf:"Word to PDF",excel2pdf:"Excel to PDF",ppt2pdf:"PowerPoint to PDF",pdf2ppt:"PDF to PowerPoint",pdf2jpg:"PDF to JPG",pdf2png:"PDF to PNG",jpg2pdf:"JPG/PNG to PDF",pdfCrop:"PDF Cropper",pdfResize:"PDF Resize",qrGenerator:"QR Code Generator",qrScanner:"QR Code Scanner",pdfText:"PDF Text Extractor",pdfImages:"PDF Image Extractor",pdfGrayscale:"PDF Grayscale",pdfCompare:"PDF Compare",pdfMeta:"PDF Metadata Viewer",blankRemove:"Blank Page Remover",pdfHeaderFooter:"PDF Header & Footer",batesNumber:"Bates Numbering",pdfMarkdown:"PDF to Markdown"},
es:{word2pdf:"Word a PDF",excel2pdf:"Excel a PDF",ppt2pdf:"PowerPoint a PDF",pdf2ppt:"PDF a PowerPoint",pdf2jpg:"PDF a JPG",pdf2png:"PDF a PNG",jpg2pdf:"JPG/PNG a PDF",pdfCrop:"Recortador de PDF",pdfResize:"Redimensionar PDF",qrGenerator:"Generador de códigos QR",qrScanner:"Escáner QR",pdfText:"Extractor de texto PDF",pdfImages:"Extractor de imágenes PDF",pdfGrayscale:"PDF en escala de grises",pdfCompare:"Comparar PDF",pdfMeta:"Visor de metadatos PDF",blankRemove:"Eliminar páginas en blanco",pdfHeaderFooter:"Encabezado y pie de PDF",batesNumber:"Numeración Bates",pdfMarkdown:"PDF a Markdown"},
fr:{word2pdf:"Word en PDF",excel2pdf:"Excel en PDF",ppt2pdf:"PowerPoint en PDF",pdf2ppt:"PDF en PowerPoint",pdf2jpg:"PDF en JPG",pdf2png:"PDF en PNG",jpg2pdf:"JPG/PNG en PDF",pdfCrop:"Recadrage PDF",pdfResize:"Redimensionner PDF",qrGenerator:"Générateur de QR",qrScanner:"Scanner QR",pdfText:"Extracteur de texte PDF",pdfImages:"Extracteur d’images PDF",pdfGrayscale:"PDF en niveaux de gris",pdfCompare:"Comparer des PDF",pdfMeta:"Métadonnées PDF",blankRemove:"Supprimer les pages vierges",pdfHeaderFooter:"En-tête et pied de page PDF",batesNumber:"Numérotation Bates",pdfMarkdown:"PDF vers Markdown"},
de:{word2pdf:"Word zu PDF",excel2pdf:"Excel zu PDF",ppt2pdf:"PowerPoint zu PDF",pdf2ppt:"PDF zu PowerPoint",pdf2jpg:"PDF zu JPG",pdf2png:"PDF zu PNG",jpg2pdf:"JPG/PNG zu PDF",pdfCrop:"PDF zuschneiden",pdfResize:"PDF-Größe ändern",qrGenerator:"QR-Code-Generator",qrScanner:"QR-Code-Scanner",pdfText:"PDF-Textextraktor",pdfImages:"PDF-Bildextraktor",pdfGrayscale:"PDF Graustufen",pdfCompare:"PDF vergleichen",pdfMeta:"PDF-Metadaten",blankRemove:"Leere PDF-Seiten entfernen",pdfHeaderFooter:"PDF Kopf- und Fußzeile",batesNumber:"Bates-Nummerierung",pdfMarkdown:"PDF zu Markdown"},
zh:{word2pdf:"Word 转 PDF",excel2pdf:"Excel 转 PDF",ppt2pdf:"PowerPoint 转 PDF",pdf2ppt:"PDF 转 PowerPoint",pdf2jpg:"PDF 转 JPG",pdf2png:"PDF 转 PNG",jpg2pdf:"JPG/PNG 转 PDF",pdfCrop:"PDF 裁剪",pdfResize:"PDF 调整大小",qrGenerator:"二维码生成器",qrScanner:"二维码扫描器",pdfText:"PDF 文本提取器",pdfImages:"PDF 图片提取器",pdfGrayscale:"PDF 灰度转换",pdfCompare:"PDF 比较",pdfMeta:"PDF 元数据查看器",blankRemove:"删除空白 PDF 页面",pdfHeaderFooter:"PDF 页眉页脚",batesNumber:"Bates 编号",pdfMarkdown:"PDF 转 Markdown"},
ja:{word2pdf:"WordをPDFに",excel2pdf:"ExcelをPDFに",ppt2pdf:"PowerPointをPDFに",pdf2ppt:"PDFをPowerPointに",pdf2jpg:"PDFをJPGに",pdf2png:"PDFをPNGに",jpg2pdf:"JPG/PNGをPDFに",pdfCrop:"PDFトリミング",pdfResize:"PDFサイズ変更",qrGenerator:"QRコード生成",qrScanner:"QRコードスキャナー",pdfText:"PDFテキスト抽出",pdfImages:"PDF画像抽出",pdfGrayscale:"PDFグレースケール",pdfCompare:"PDF比較",pdfMeta:"PDFメタデータ",blankRemove:"空白ページ削除",pdfHeaderFooter:"PDFヘッダーとフッター",batesNumber:"Bates番号",pdfMarkdown:"PDFをMarkdownに"},
ru:{word2pdf:"Word в PDF",excel2pdf:"Excel в PDF",ppt2pdf:"PowerPoint в PDF",pdf2ppt:"PDF в PowerPoint",pdf2jpg:"PDF в JPG",pdf2png:"PDF в PNG",jpg2pdf:"JPG/PNG в PDF",pdfCrop:"Обрезка PDF",pdfResize:"Изменение размера PDF",qrGenerator:"Генератор QR-кодов",qrScanner:"Сканер QR-кодов",pdfText:"Извлечение текста PDF",pdfImages:"Извлечение изображений PDF",pdfGrayscale:"PDF в градациях серого",pdfCompare:"Сравнение PDF",pdfMeta:"Метаданные PDF",blankRemove:"Удаление пустых страниц",pdfHeaderFooter:"Колонтитулы PDF",batesNumber:"Нумерация Bates",pdfMarkdown:"PDF в Markdown"},
ar:{word2pdf:"Word إلى PDF",excel2pdf:"Excel إلى PDF",ppt2pdf:"PowerPoint إلى PDF",pdf2ppt:"PDF إلى PowerPoint",pdf2jpg:"PDF إلى JPG",pdf2png:"PDF إلى PNG",jpg2pdf:"JPG/PNG إلى PDF",pdfCrop:"قص PDF",pdfResize:"تغيير حجم PDF",qrGenerator:"مولد رمز QR",qrScanner:"ماسح QR",pdfText:"استخراج نص PDF",pdfImages:"استخراج صور PDF",pdfGrayscale:"PDF بتدرج الرمادي",pdfCompare:"مقارنة PDF",pdfMeta:"بيانات PDF الوصفية",blankRemove:"حذف الصفحات الفارغة",pdfHeaderFooter:"رأس وتذييل PDF",batesNumber:"ترقيم Bates",pdfMarkdown:"PDF إلى Markdown"},
pt:{word2pdf:"Word para PDF",excel2pdf:"Excel para PDF",ppt2pdf:"PowerPoint para PDF",pdf2ppt:"PDF para PowerPoint",pdf2jpg:"PDF para JPG",pdf2png:"PDF para PNG",jpg2pdf:"JPG/PNG para PDF",pdfCrop:"Cortar PDF",pdfResize:"Redimensionar PDF",qrGenerator:"Gerador de QR Code",qrScanner:"Leitor de QR Code",pdfText:"Extrator de texto PDF",pdfImages:"Extrator de imagens PDF",pdfGrayscale:"PDF em escala de cinza",pdfCompare:"Comparar PDFs",pdfMeta:"Metadados do PDF",blankRemove:"Remover páginas em branco",pdfHeaderFooter:"Cabeçalho e rodapé PDF",batesNumber:"Numeração Bates",pdfMarkdown:"PDF para Markdown"},
it:{word2pdf:"Word in PDF",excel2pdf:"Excel in PDF",ppt2pdf:"PowerPoint in PDF",pdf2ppt:"PDF in PowerPoint",pdf2jpg:"PDF in JPG",pdf2png:"PDF in PNG",jpg2pdf:"JPG/PNG in PDF",pdfCrop:"Ritaglia PDF",pdfResize:"Ridimensiona PDF",qrGenerator:"Generatore QR",qrScanner:"Scanner QR",pdfText:"Estrattore testo PDF",pdfImages:"Estrattore immagini PDF",pdfGrayscale:"PDF in scala di grigi",pdfCompare:"Confronta PDF",pdfMeta:"Metadati PDF",blankRemove:"Rimuovi pagine vuote",pdfHeaderFooter:"Intestazione e piè di pagina PDF",batesNumber:"Numerazione Bates",pdfMarkdown:"PDF in Markdown"},
hi:{word2pdf:"Word से PDF",excel2pdf:"Excel से PDF",ppt2pdf:"PowerPoint से PDF",pdf2ppt:"PDF से PowerPoint",pdf2jpg:"PDF से JPG",pdf2png:"PDF से PNG",jpg2pdf:"JPG/PNG से PDF",pdfCrop:"PDF क्रॉपर",pdfResize:"PDF आकार बदलें",qrGenerator:"QR कोड जनरेटर",qrScanner:"QR कोड स्कैनर",pdfText:"PDF टेक्स्ट एक्सट्रैक्टर",pdfImages:"PDF इमेज एक्सट्रैक्टर",pdfGrayscale:"PDF ग्रेस्केल",pdfCompare:"PDF तुलना",pdfMeta:"PDF मेटाडेटा व्यूअर",blankRemove:"खाली PDF पेज हटाएँ",pdfHeaderFooter:"PDF हेडर और फुटर",batesNumber:"Bates नंबरिंग",pdfMarkdown:"PDF से Markdown"}};
window.SmartPDFNewToolTitle=(id,lang)=>((NT_NAMES[lang]||NT_NAMES.en)[id]||NT_NAMES.en[id]);window.SmartPDFNewToolIds=T.map(x=>x[0]);
window.SmartPDFNewToolUI=(id,ctx)=>{let{c,k,C}=ctx,hi=C==="hi",field={word2pdf:["word2pdfFile",".docx"],excel2pdf:["excel2pdfFile",".xlsx,.xls,.csv"],ppt2pdf:["ppt2pdfFile",".pptx"],pdf2ppt:["pdf2pptFile",".pdf"],pdf2jpg:["pdf2jpgFile",".pdf"],pdf2png:["pdf2pngFile",".pdf"],jpg2pdf:["jpg2pdfFiles","image/jpeg,image/png"],pdfCrop:["pdfCropFile",".pdf"],pdfResize:["pdfResizeFile",".pdf"],qrScanner:["qrScanFile","image/*"],pdfText:["pdfTextFile",".pdf"],pdfImages:["pdfImagesFile",".pdf"],pdfGrayscale:["pdfGrayscaleFile",".pdf"],pdfMeta:["pdfMetaFile",".pdf"],blankRemove:["blankRemoveFile",".pdf"],pdfMarkdown:["pdfMarkdownFile",".pdf"],pdfHeaderFooter:["pdfHeaderFooterFile",".pdf"],batesNumber:["batesFile",".pdf"]}[id],inp=(x,a,m)=>c("input",{id:x,type:"file",accept:a,multiple:!!m,className:"w-full rounded-xl border border-slate-200 p-3 text-sm bg-slate-50"}),body=field?inp(field[0],field[1],id==="jpg2pdf"):null;let label=hi?"फ़ाइल चुनें":"Choose file";if(id==="pdfCrop")body=k("div",{className:"space-y-2",children:[body,c("input",{id:"crop",type:"number",defaultValue:"10",placeholder:hi?"क्रॉप मार्जिन":"Crop margin",className:"w-full rounded-xl border p-3 text-sm"})]});if(id==="pdfResize")body=k("div",{className:"space-y-2",children:[body,c("select",{id:"size",className:"w-full rounded-xl border p-3 text-sm",children:["a4","letter","a5"].map(x=>c("option",{value:x,children:x.toUpperCase()}))})]});if(id==="qrGenerator")body=k("div",{className:"space-y-2",children:[c("textarea",{id:"qrText",rows:4,placeholder:hi?"टेक्स्ट या URL":"Text or URL",className:"w-full rounded-xl border p-3 text-sm"}),c("input",{id:"qrSize",type:"number",defaultValue:"512",className:"w-full rounded-xl border p-3 text-sm"})]});if(id==="qrScanner")body=inp("qrScanFile","image/*");if(id==="pdfCompare")body=k("div",{className:"space-y-2",children:[inp("pdfCompareA",".pdf"),inp("pdfCompareB",".pdf")]});if(id==="pdfHeaderFooter")body=k("div",{className:"space-y-2",children:[body,c("input",{id:"head",placeholder:hi?"हेडर":"Header",className:"w-full rounded-xl border p-3 text-sm"}),c("input",{id:"foot",placeholder:hi?"फुटर":"Footer",className:"w-full rounded-xl border p-3 text-sm"})]});if(id==="batesNumber")body=k("div",{className:"space-y-2",children:[body,c("input",{id:"pre",defaultValue:"CASE-",placeholder:hi?"प्रिफिक्स":"Prefix",className:"w-full rounded-xl border p-3 text-sm"}),c("input",{id:"start",type:"number",defaultValue:"1",placeholder:hi?"शुरुआती नंबर":"Start number",className:"w-full rounded-xl border p-3 text-sm"})]});return k("div",{className:"space-y-4",children:[c("p",{className:"text-xs text-slate-500","data-i18n":"" ,children:label}),body]})};
window.SmartPDFNewToolProcess=async id=>run(id);

})();