import { ToolDefinition } from '../types';

export const TOOLS: ToolDefinition[] = [
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    category: 'Image',
    popular: true,
    description: 'Reduce image file size while maintaining quality with client-side compression.',
    shortDescription: 'Reduce image size without quality loss.',
    iconName: 'image-compressor',
    inputType: 'image',
    outputType: 'image',
    keywords: ['compress', 'image', 'photo', 'shrink', 'jpg', 'png', 'webp', 'reduce size'],
  },
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    category: 'Organize',
    popular: true,
    description: 'Combine multiple PDF files into a single unified document in seconds.',
    shortDescription: 'Combine multiple PDFs into one.',
    iconName: 'merge-pdf',
    inputType: 'multiple-pdf',
    outputType: 'pdf',
    keywords: ['merge', 'combine', 'join', 'unite', 'multiple', 'pdf'],
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    category: 'PDF',
    description: 'Reduce PDF file size for easy sharing, archiving, and uploading.',
    shortDescription: 'Reduce PDF file size quickly.',
    iconName: 'compress-pdf',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['compress', 'pdf', 'shrink', 'optimize', 'reduce'],
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    category: 'Convert',
    popular: true,
    description: 'Extract readable PDF text into a Word-compatible document. Complex layouts may require manual cleanup.',
    shortDescription: 'Convert PDF into editable Word.',
    iconName: 'pdf-to-word',
    inputType: 'pdf',
    outputType: 'docx',
    keywords: ['word', 'docx', 'convert', 'doc', 'editable', 'text'],
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    category: 'Convert',
    description: 'Extract pages from your PDF file and save them as high-quality JPG images.',
    shortDescription: 'Save PDF pages as JPG photos.',
    iconName: 'pdf-to-jpg',
    inputType: 'pdf',
    outputType: 'image',
    keywords: ['pdf to jpg', 'images', 'extract', 'photos', 'convert'],
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    category: 'Organize',
    description: 'Extract individual pages or separate page ranges into separate PDF documents.',
    shortDescription: 'Separate PDF into multiple files.',
    iconName: 'split-pdf',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['split', 'cut', 'pages', 'separate', 'extract', 'range'],
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    category: 'Convert',
    description: 'Extract data and tabular figures from PDF directly into Excel spreadsheets.',
    shortDescription: 'Extract PDF data to Excel tables.',
    iconName: 'pdf-to-excel',
    inputType: 'pdf',
    outputType: 'xlsx',
    keywords: ['excel', 'xlsx', 'spreadsheet', 'table', 'data'],
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    category: 'Convert',
    popular: true,
    description: 'Convert JPG, JPEG, and PNG images into a clean professional PDF file.',
    shortDescription: 'Transform photos into a PDF.',
    iconName: 'jpg-to-pdf',
    inputType: 'image',
    outputType: 'pdf',
    keywords: ['jpg to pdf', 'photo to pdf', 'image', 'png', 'jpeg'],
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    category: 'Edit',
    description: 'Rotate PDF pages 90, 180, or 270 degrees and permanently save the new orientation.',
    shortDescription: 'Rotate pages in any direction.',
    iconName: 'rotate-pdf',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['rotate', 'turn', 'orientation', 'upside down', 'landscape', 'portrait'],
  },
  {
    id: 'watermark-pdf',
    name: 'Watermark PDF',
    category: 'Security',
    description: 'Add custom text watermarks, stamps, or copyright notices across your PDF pages.',
    shortDescription: 'Stamp text watermark on PDF.',
    iconName: 'watermark-pdf',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['watermark', 'stamp', 'copyright', 'confidential', 'draft'],
  },
  {
    id: 'page-numbers',
    name: 'Page Numbers',
    category: 'Edit',
    description: 'Insert clean page numbers at top or bottom with custom positions and format.',
    shortDescription: 'Add page numbers to document.',
    iconName: 'page-numbers',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['page numbers', 'paginate', 'numbering', 'footer', 'header'],
  },
  {
    id: 'crop-pdf',
    name: 'Crop PDF',
    category: 'Edit',
    description: 'Trim margins or crop specific visible areas of your PDF pages.',
    shortDescription: 'Trim margins and crop pages.',
    iconName: 'crop-pdf',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['crop', 'trim', 'margins', 'cutout', 'resize'],
  },
  {
    id: 'resize-pdf',
    name: 'Resize PDF',
    category: 'Edit',
    description: 'Change the dimensions of PDF pages to standard sizes (A4, Letter, Legal).',
    shortDescription: 'Change PDF page dimensions.',
    iconName: 'resize-pdf',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['resize', 'page size', 'a4', 'letter', 'dimensions'],
  },
  {
    id: 'extract-pages',
    name: 'Extract Pages',
    category: 'Organize',
    description: 'Select specific page numbers from a PDF and save them as a brand new document.',
    shortDescription: 'Extract chosen pages to new PDF.',
    iconName: 'extract-pages',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['extract', 'select pages', 'pull pages', 'export'],
  },
  {
    id: 'remove-pages',
    name: 'Remove Pages',
    category: 'Organize',
    description: 'Delete unwanted, blank, or sensitive pages from your PDF file.',
    shortDescription: 'Delete unwanted pages from PDF.',
    iconName: 'remove-pages',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['remove', 'delete', 'cut page', 'trash page'],
  },
  {
    id: 'reorder-pages',
    name: 'Reorder Pages',
    category: 'Organize',
    description: 'Rearrange and change the order of pages inside your PDF document.',
    shortDescription: 'Rearrange page sequences.',
    iconName: 'reorder-pages',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['reorder', 'sort', 'arrange', 'sequence'],
  },
  {
    id: 'duplicate-pages',
    name: 'Duplicate Pages',
    category: 'Organize',
    description: 'Clone or duplicate specific pages within your PDF.',
    shortDescription: 'Duplicate pages inside PDF.',
    iconName: 'duplicate-pages',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['duplicate', 'clone', 'repeat', 'copy page'],
  },
  {
    id: 'organize-pdf',
    name: 'Organize PDF',
    category: 'Organize',
    description: 'Visual grid manager to delete, rotate, and sort PDF pages with one click.',
    shortDescription: 'Visual page organizer.',
    iconName: 'organize-pdf',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['organize', 'manager', 'grid', 'sort', 'pages'],
  },
  {
    id: 'pdf-to-png',
    name: 'PDF to PNG',
    category: 'Convert',
    description: 'Convert PDF pages into transparent, crisp, high-resolution PNG graphics.',
    shortDescription: 'Convert PDF pages to PNG.',
    iconName: 'pdf-to-png',
    inputType: 'pdf',
    outputType: 'image',
    keywords: ['png', 'transparent', 'convert', 'high resolution'],
  },
  {
    id: 'pdf-to-text',
    name: 'PDF to Text',
    category: 'Convert',
    description: 'Extract raw selectable text from your PDF into a clean plain text file.',
    shortDescription: 'Extract plain text from PDF.',
    iconName: 'pdf-to-text',
    inputType: 'pdf',
    outputType: 'txt',
    keywords: ['text', 'txt', 'extract', 'content', 'copy text'],
  },
  {
    id: 'ocr-pdf',
    name: 'OCR PDF',
    category: 'Convert',
    description: 'Recognize scanned document text with optical character recognition.',
    shortDescription: 'Optical text recognition for PDF.',
    iconName: 'ocr-pdf',
    inputType: 'pdf',
    outputType: 'txt',
    keywords: ['ocr', 'scan', 'recognition', 'searchable', 'detect text'],
  },
  {
    id: 'image-ocr',
    name: 'Image OCR',
    category: 'Image',
    description: 'Extract text from screenshots, scanned photos, and receipts directly in browser.',
    shortDescription: 'Extract text from photo/scan.',
    iconName: 'image-ocr',
    inputType: 'image',
    outputType: 'txt',
    keywords: ['ocr', 'image to text', 'screenshot text', 'extract text'],
  },
  {
    id: 'text-to-pdf',
    name: 'Text to PDF',
    category: 'Create',
    description: 'Convert raw text, notes, or code blocks into a formatted PDF document.',
    shortDescription: 'Generate PDF from raw text.',
    iconName: 'text-to-pdf',
    inputType: 'text',
    outputType: 'pdf',
    keywords: ['text to pdf', 'txt', 'create', 'generate'],
  },
  {
    id: 'html-to-pdf',
    name: 'HTML to PDF',
    category: 'Create',
    description: 'Render HTML snippets, templates, or articles into formatted PDF files.',
    shortDescription: 'Render HTML code to PDF.',
    iconName: 'html-to-pdf',
    inputType: 'text',
    outputType: 'pdf',
    keywords: ['html', 'webpage', 'css', 'code to pdf'],
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    category: 'Convert',
    description: 'Convert Word documents (.docx, .doc) into high-fidelity PDF format.',
    shortDescription: 'Convert Word docs to PDF.',
    iconName: 'word-to-pdf',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['word to pdf', 'docx to pdf', 'doc', 'office'],
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    category: 'Convert',
    description: 'Convert Excel tables and spreadsheets (.xlsx) into clean printable PDFs.',
    shortDescription: 'Convert Excel sheets to PDF.',
    iconName: 'excel-to-pdf',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['excel to pdf', 'xlsx to pdf', 'sheet', 'table'],
  },
  {
    id: 'powerpoint-to-pdf',
    name: 'PowerPoint to PDF',
    category: 'Convert',
    description: 'Convert PPT and PPTX slide presentations into portable PDF slides.',
    shortDescription: 'Convert slides into PDF.',
    iconName: 'powerpoint-to-pdf',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['powerpoint', 'pptx', 'presentation', 'slides'],
  },
  {
    id: 'pdf-to-powerpoint',
    name: 'PDF to PowerPoint',
    category: 'Convert',
    description: 'Convert PDF pages into PowerPoint presentation slides (.pptx).',
    shortDescription: 'Convert PDF into PPT slides.',
    iconName: 'pdf-to-powerpoint',
    inputType: 'pdf',
    outputType: 'pptx',
    keywords: ['pdf to ppt', 'powerpoint', 'slides', 'convert'],
  },
  {
    id: 'pdf-to-pdfa',
    name: 'PDF to PDF/A',
    category: 'PDF',
    description: 'Convert your PDF to ISO-standard PDF/A for long-term archiving and compliance.',
    shortDescription: 'Standardize PDF for archiving.',
    iconName: 'pdf-to-pdfa',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['pdf/a', 'archive', 'compliance', 'iso', 'long term'],
  },
  {
    id: 'pdf-metadata',
    name: 'PDF Metadata',
    category: 'PDF',
    description: 'Inspect and edit PDF document properties (Title, Author, Subject, Keywords).',
    shortDescription: 'Edit PDF title, author & metadata.',
    iconName: 'pdf-metadata',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['metadata', 'author', 'title', 'keywords', 'properties'],
  },
  {
    id: 'flatten-pdf',
    name: 'Flatten PDF',
    category: 'Edit',
    description: 'Flatten interactive form fields and annotations into static non-editable page content.',
    shortDescription: 'Flatten forms and annotations.',
    iconName: 'flatten-pdf',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['flatten', 'static', 'forms', 'lock fields', 'non-editable'],
  },
  {
    id: 'header-footer',
    name: 'Header & Footer',
    category: 'Edit',
    description: 'Add custom recurring headers, footers, dates, and titles across PDF pages.',
    shortDescription: 'Add custom headers and footers.',
    iconName: 'header-footer',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['header', 'footer', 'title', 'date', 'page numbering'],
  },
  {
    id: 'pdf-annotation',
    name: 'PDF Annotation',
    category: 'Edit',
    description: 'Annotate PDF with highlights, custom callouts, lines, and sticky notes.',
    shortDescription: 'Add highlights and markup.',
    iconName: 'pdf-annotation',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['annotate', 'highlight', 'notes', 'markup', 'draw'],
  },
  {
    id: 'sign-pdf',
    name: 'Sign PDF',
    category: 'Security',
    description: 'Draw, type, or upload your electronic signature and place it on any page.',
    shortDescription: 'Sign PDF document electronically.',
    iconName: 'sign-pdf',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['sign', 'signature', 'e-sign', 'contract', 'signature pad'],
  },
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    category: 'Security',
    description: 'Encrypt your PDF with a secure password to prevent unauthorized viewing.',
    shortDescription: 'Add password encryption to PDF.',
    iconName: 'protect-pdf',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['protect', 'password', 'lock', 'encrypt', 'security'],
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    category: 'Security',
    description: 'Remove password protection from your PDF so you can open it without prompt.',
    shortDescription: 'Remove PDF password lock.',
    iconName: 'unlock-pdf',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['unlock', 'remove password', 'decrypt', 'open'],
  },
  {
    id: 'encrypt-pdf',
    name: 'Encrypt PDF',
    category: 'Security',
    description: 'Apply advanced 128-bit or 256-bit encryption rules to protect sensitive documents.',
    shortDescription: 'Apply strong document encryption.',
    iconName: 'encrypt-pdf',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['encrypt', 'security', 'aes', 'secure', 'confidential'],
  },
  {
    id: 'redact-pdf',
    name: 'Redact PDF',
    category: 'Security',
    description: 'Permanently blackout and erase confidential numbers, names, and sensitive areas.',
    shortDescription: 'Blackout sensitive text/areas.',
    iconName: 'redact-pdf',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['redact', 'blackout', 'privacy', 'censor', 'remove private data'],
  },
  {
    id: 'compare-pdfs',
    name: 'Compare PDFs',
    category: 'Utilities',
    description: 'Compare two PDF documents side by side to quickly inspect visual changes.',
    shortDescription: 'Side-by-side document comparison.',
    iconName: 'compare-pdfs',
    inputType: 'multiple-pdf',
    outputType: 'info',
    keywords: ['compare', 'diff', 'side by side', 'differences', 'revision'],
  },
  {
    id: 'pdf-page-preview',
    name: 'PDF Page Preview',
    category: 'PDF',
    description: 'Preview every page in your PDF document with responsive thumbnail inspection.',
    shortDescription: 'Inspect PDF page thumbnails.',
    iconName: 'pdf-page-preview',
    inputType: 'pdf',
    outputType: 'info',
    keywords: ['preview', 'thumbnails', 'viewer', 'inspect', 'pages'],
  },
  {
    id: 'pdf-info',
    name: 'PDF Info',
    category: 'Utilities',
    description: 'View file technical details: version, page count, dimensions, creator, and font list.',
    shortDescription: 'Inspect technical document details.',
    iconName: 'pdf-info',
    inputType: 'pdf',
    outputType: 'info',
    keywords: ['info', 'details', 'pages', 'size', 'creator', 'specs'],
  },
  {
    id: 'search-pdf',
    name: 'Search PDF',
    category: 'Utilities',
    description: 'Search for phrases, keywords, and text occurrences throughout entire PDF.',
    shortDescription: 'Find words inside PDF document.',
    iconName: 'search-pdf',
    inputType: 'pdf',
    outputType: 'info',
    keywords: ['search', 'find text', 'keywords', 'occurrences'],
  },
  {
    id: 'pdf-split-by-count',
    name: 'PDF Split by Count',
    category: 'Organize',
    description: 'Split a large document into equal parts by page count (e.g. 5 pages per file).',
    shortDescription: 'Split by fixed page counts.',
    iconName: 'pdf-split-by-count',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['split count', 'batch split', 'chunks', 'pages'],
  },
  {
    id: 'split-every-n-pages',
    name: 'Split Every N Pages',
    category: 'Organize',
    description: 'Automatically segment your PDF into separate files every N pages.',
    shortDescription: 'Split PDF periodically.',
    iconName: 'split-every-n-pages',
    inputType: 'pdf',
    outputType: 'pdf',
    keywords: ['split n', 'periodic', 'segments', 'interval'],
  },
  {
    id: 'images-to-pdf',
    name: 'Images to PDF',
    category: 'Convert',
    description: 'Batch convert a sequence of photos (JPG, PNG, WebP) into a multi-page PDF.',
    shortDescription: 'Batch photos into one PDF.',
    iconName: 'images-to-pdf',
    inputType: 'multiple-images',
    outputType: 'pdf',
    keywords: ['images to pdf', 'batch images', 'album', 'photos to pdf'],
  },
  {
    id: 'scan-to-pdf',
    name: 'Scan to PDF',
    category: 'Create',
    description: 'Capture documents with your device camera or webcam directly into a crisp PDF.',
    shortDescription: 'Capture via camera to PDF.',
    iconName: 'scan-to-pdf',
    inputType: 'none',
    outputType: 'pdf',
    keywords: ['scan', 'camera', 'webcam', 'capture', 'mobile scan'],
  },
  {
    id: 'qr-code-to-pdf',
    name: 'QR Code to PDF',
    category: 'Create',
    description: 'Generate high-resolution printable QR codes placed onto PDF pages.',
    shortDescription: 'Generate printable QR code PDF.',
    iconName: 'qr-code-to-pdf',
    inputType: 'text',
    outputType: 'pdf',
    keywords: ['qr code to pdf', 'printable qr', 'barcode pdf', 'scan code'],
  },
  {
    id: 'qr-code-maker',
    name: 'QR Code Maker',
    category: 'Utilities',
    description: 'Generate a browser-side QR-style image for text and URLs.',
    shortDescription: 'Create custom QR codes.',
    iconName: 'qr-code-maker',
    inputType: 'text',
    outputType: 'image',
    keywords: ['qr code maker', 'generator', 'wifi qr', 'link qr', 'png', 'svg'],
  },
  {
    id: 'barcode-maker',
    name: 'Barcode Maker',
    category: 'Utilities',
    description: 'Generate a browser-side barcode-style image from text.',
    shortDescription: 'Create standard barcodes.',
    iconName: 'barcode-maker',
    inputType: 'text',
    outputType: 'image',
    keywords: ['barcode', 'code 128', 'inventory', 'sku', 'retail'],
  },
  {
    id: 'invoice-maker',
    name: 'Invoice Maker',
    category: 'Create',
    description: 'Create professional business invoices with line items, tax, and company branding.',
    shortDescription: 'Generate professional invoices.',
    iconName: 'invoice-maker',
    inputType: 'form',
    outputType: 'pdf',
    keywords: ['invoice', 'bill', 'receipt', 'tax', 'business', 'create invoice'],
  },
  {
    id: 'resume-builder',
    name: 'Resume Builder',
    category: 'Create',
    description: 'Build a polished, modern curriculum vitae and download clean PDF resumes.',
    shortDescription: 'Build modern CV / Resume PDF.',
    iconName: 'resume-builder',
    inputType: 'form',
    outputType: 'pdf',
    keywords: ['resume', 'cv', 'curriculum vitae', 'job application', 'career'],
  },
  {
    id: 'certificate-maker',
    name: 'Certificate Maker',
    category: 'Create',
    description: 'Design elegant certificates of completion, appreciation, and achievement.',
    shortDescription: 'Design award certificates.',
    iconName: 'certificate-maker',
    inputType: 'form',
    outputType: 'pdf',
    keywords: ['certificate', 'award', 'diploma', 'completion', 'achievement'],
  },
  {
    id: 'letter-to-pdf',
    name: 'Letter to PDF',
    category: 'Create',
    description: 'Write formal business letters with sender/recipient details and letterheads.',
    shortDescription: 'Format formal letter to PDF.',
    iconName: 'letter-to-pdf',
    inputType: 'form',
    outputType: 'pdf',
    keywords: ['letter', 'formal letter', 'cover letter', 'business letter'],
  },
  {
    id: 'poster-to-pdf',
    name: 'Poster to PDF',
    category: 'Create',
    description: 'Create eye-catching announcement posters, event flyers, and notices.',
    shortDescription: 'Design event posters & flyers.',
    iconName: 'poster-to-pdf',
    inputType: 'form',
    outputType: 'pdf',
    keywords: ['poster', 'flyer', 'notice', 'announcement', 'event'],
  },
  {
    id: 'compress-image',
    name: 'Compress Image',
    category: 'Image',
    description: 'Compress individual or multiple photos while maintaining vivid clarity.',
    shortDescription: 'Compress photos with slider control.',
    iconName: 'compress-image',
    inputType: 'image',
    outputType: 'image',
    keywords: ['compress image', 'photo compressor', 'shrink jpg', 'optimize png'],
  },
  {
    id: 'resize-image',
    name: 'Resize Image',
    category: 'Image',
    description: 'Change image pixel dimensions (width/height) with aspect ratio lock.',
    shortDescription: 'Resize image dimensions.',
    iconName: 'resize-image',
    inputType: 'image',
    outputType: 'image',
    keywords: ['resize image', 'scale photo', 'dimensions', 'width', 'height'],
  },
  {
    id: 'convert-image',
    name: 'Convert Image',
    category: 'Image',
    description: 'Convert between PNG, JPG, and WEBP formats directly in the browser.',
    shortDescription: 'Convert between JPG, PNG & WebP.',
    iconName: 'convert-image',
    inputType: 'image',
    outputType: 'image',
    keywords: ['convert image', 'jpg to png', 'png to jpg', 'webp converter'],
  },
  {
    id: 'crop-image',
    name: 'Crop Image',
    category: 'Image',
    description: 'Crop photos to custom rectangular dimensions or popular aspect ratios.',
    shortDescription: 'Crop image to aspect ratios.',
    iconName: 'crop-image',
    inputType: 'image',
    outputType: 'image',
    keywords: ['crop image', 'crop photo', 'cut picture', 'aspect ratio'],
  },
  {
    id: 'sign-image',
    name: 'Sign Image',
    category: 'Image',
    description: 'Stamp your handwritten signature or watermark onto any photo or graphic.',
    shortDescription: 'Stamp signature onto photos.',
    iconName: 'sign-image',
    inputType: 'image',
    outputType: 'image',
    keywords: ['sign image', 'sign photo', 'watermark photo', 'signature stamp'],
  },
  {
    id: 'color-picker',
    name: 'Color Picker',
    category: 'Utilities',
    description: 'Pick colors from uploaded images or documents with HEX, RGB, and HSL palettes.',
    shortDescription: 'Pick colors from files & images.',
    iconName: 'color-picker',
    inputType: 'image',
    outputType: 'info',
    keywords: ['color picker', 'eyedropper', 'palette', 'hex', 'rgb', 'sample colors'],
  },
];

export const POPULAR_TOOL_IDS = ['image-compressor', 'pdf-to-word', 'merge-pdf', 'jpg-to-pdf'];

export const CATEGORIES = [
  'All',
  'PDF',
  'Convert',
  'Edit',
  'Organize',
  'Security',
  'Create',
  'Image',
  'Utilities',
] as const;

export const VISUAL_CATEGORIES = [
  {
    id: 'convert-to-pdf',
    title: 'Convert to PDF',
    count: '8 Tools',
    description: 'Convert images, Word, Excel, text and slides into PDF.',
    icon: 'cat-convert-to-pdf',
    filterCategory: 'Convert',
  },
  {
    id: 'convert-from-pdf',
    title: 'Convert from PDF',
    count: '7 Tools',
    description: 'Export PDF documents to Word, Excel, images & text.',
    icon: 'cat-convert-from-pdf',
    filterCategory: 'Convert',
  },
  {
    id: 'organize-pdf',
    title: 'Organize PDF',
    count: '8 Tools',
    description: 'Merge, split, reorder, extract, and sort pages.',
    icon: 'cat-organize-pdf',
    filterCategory: 'Organize',
  },
  {
    id: 'edit-pdf',
    title: 'Edit PDF',
    count: '8 Tools',
    description: 'Rotate, crop, watermark, annotate, and number pages.',
    icon: 'cat-edit-pdf',
    filterCategory: 'Edit',
  },
  {
    id: 'security',
    title: 'Security',
    count: '6 Tools',
    description: 'Protect, unlock, sign, encrypt, and redact PDFs.',
    icon: 'cat-security',
    filterCategory: 'Security',
  },
  {
    id: 'image-tools',
    title: 'Image Tools',
    count: '7 Tools',
    description: 'Compress, resize, convert, crop, and OCR photos.',
    icon: 'cat-image-tools',
    filterCategory: 'Image',
  },
  {
    id: 'utilities',
    title: 'Utilities',
    count: '8 Tools',
    description: 'QR maker, barcodes, color picker, and comparisons.',
    icon: 'cat-utilities',
    filterCategory: 'Utilities',
  },
  {
    id: 'more-tools',
    title: 'More Tools',
    count: '8 Tools',
    description: 'Invoices, resumes, certificates, and scan utilities.',
    icon: 'cat-more-tools',
    filterCategory: 'Create',
  },
];
